name: Terraform CI

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Download kubernetes module
        run: pip install --target k3s_cluster/lambda/kube_cleaner_src/ kubernetes
      
      - name: create lambda func zip
        run: zip -r ../kube_cleaner.zip .
        working-directory: k3s_cluster/lambda/kube_cleaner_src/

      - name: Run a Terraform init
        uses: docker://hashicorp/terraform:light
        with:
          entrypoint: terraform
          args: init

      - name: Run a Terraform validate
        uses: docker://hashicorp/terraform:light
        with:
          entrypoint: terraform
          args: validate

      - name: Run a Terraform fmt
        uses: docker://hashicorp/terraform:light
        with:
          entrypoint: terraform
          args: fmt  --recursive -check=true --diff k3s_cluster/